Genepop 4.6.9: Hardy-Weinberg test

File: /home/gasta/Documents/GitHub/biopython/Tests/PopGen/big.gen (Data from CSV file)

Number of populations detected:    10
Number of loci detected:           37


Hardy-Weinberg exact test for up to four alleles.
 (complete enumeration)
Hardy Weinberg test when H1= heterozygote excess
                         ***********************


==========================================
     Results by locus
==========================================


Locus "Locus1"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.4955    -     -0.1600 -0.1623      5 matrices
Ind31       0.9825    -     -0.0182 -0.0185      2 matrices
Ind31       0.6844    -     -0.1111 -0.1127      4 matrices
Ind32       0.9699    -      0.2077  0.2119      4 matrices
Ind15        - 
Ind31       0.8233    -     -0.0800 -0.0813      3 matrices
Ind31       0.7511    -     -0.0980 -0.0996      4 matrices
Ind31       0.7591    -     -0.0943 -0.0958      4 matrices
Ind31       0.7879    -      0.0217  0.0221      6 matrices
Ind41       0.5732    -     -0.1429 -0.1450      5 matrices

Locus "Locus2"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.6844    -     -0.1111 -0.1127      4 matrices
Ind31       0.6644    -     -0.1200 -0.1218      4 matrices
Ind31       0.7116    -     -0.1429 -0.1466      3 matrices
Ind32       0.6753    -     -0.0332 -0.0338      7 matrices
Ind15        - 
Ind31        - 
Ind31        - 
Ind31       0.5856    -     -0.1373 -0.1393      5 matrices
Ind31       1.0000    -      0.6545  0.6828      2 matrices
Ind41       0.8453    -      0.0569  0.0579      6 matrices

Locus "Locus3"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.9956    -      0.3919  0.4009     12 matrices
Ind31       0.4862    -     -0.0821 -0.0834     11 matrices
Ind31       0.6327    -     -0.0286 -0.0293     10 matrices
Ind32       0.1816    -     -0.2383 -0.2415     14 matrices
Ind15        - 
Ind31       0.6704    -      0.0110  0.0112     13 matrices
Ind31       0.8581    -      0.1166  0.1192      9 matrices
Ind31       0.4984    -     -0.0691 -0.0702     14 matrices
Ind31       0.9964    -      0.4624  0.4790      7 matrices
Ind41       0.7367    -      0.0447  0.0455     13 matrices

Locus "Locus4"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31        - 
Ind31       0.9519    -      0.2162  0.2207      8 matrices
Ind31       0.8402    -     -0.0714 -0.0725      3 matrices
Ind32       0.8293    -     -0.0769 -0.0782      3 matrices
Ind15       0.9689    -      0.2826  0.2986      3 matrices
Ind31       0.9508    -     -0.0345 -0.0350      2 matrices
Ind31       0.9953    -      0.3922  0.4015      8 matrices
Ind31       0.9025    -     -0.0526 -0.0534      3 matrices
Ind31        - 
Ind41       0.9859    -      0.2996  0.3060      6 matrices

Locus "Locus5"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.2793    -     -0.1837 -0.1862     11 matrices
Ind31       0.9421    -      0.1512  0.1542      5 matrices
Ind31       0.7039    -      0.0055  0.0056      9 matrices
Ind32       0.5732    -     -0.1429 -0.1450      5 matrices
Ind15       0.8696    -     -0.1000 -0.1039      2 matrices
Ind31       0.9789    -      0.2857  0.2918      9 matrices
Ind31       0.7665    -     -0.0909 -0.0923      4 matrices
Ind31       0.7753    -      0.0151  0.0154      6 matrices
Ind31       0.0405    -     -0.3810 -0.3849      9 matrices
Ind41       0.8402    -     -0.0714 -0.0725      3 matrices

Locus "Locus6"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.9025    -     -0.0526 -0.0534      3 matrices
Ind31        - 
Ind31        - 
Ind32        - 
Ind15       0.8696    -     -0.1000 -0.1039      2 matrices
Ind31        - 
Ind31       1.0000    -      0.6591  0.6772      2 matrices
Ind31        - 
Ind31        - 
Ind41       0.9455    -     -0.0385 -0.0391      2 matrices

Locus "Locus7"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.9025    -     -0.0526 -0.0534      3 matrices
Ind31        - 
Ind31        - 
Ind32        - 
Ind15       0.7453    -     -0.1579 -0.1636      3 matrices
Ind31       0.8402    -     -0.0714 -0.0725      3 matrices
Ind31       0.9958    -      0.3617  0.3698      3 matrices
Ind31        - 
Ind31       0.9025    -     -0.0526 -0.0534      3 matrices
Ind41       0.9474    -     -0.0370 -0.0377      2 matrices

Locus "Locus8"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.9661    -      0.2551  0.2603     12 matrices
Ind31       0.2606    -     -0.1837 -0.1862     16 matrices
Ind31       0.4778    -     -0.0943 -0.0958     10 matrices
Ind32       0.6733    -      0.0000  0.0000     10 matrices
Ind15       0.5101    -     -0.2381 -0.2448      4 matrices
Ind31       0.1180    -     -0.2960 -0.2998     13 matrices
Ind31       0.9930    -      0.3935  0.4048      9 matrices
Ind31       0.9840    -      0.3103  0.3170     12 matrices
Ind31       0.6555    -     -0.0182 -0.0185      9 matrices
Ind41       0.9753    -      0.2771  0.2829     11 matrices

Locus "Locus9"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31        - 
Ind31       0.5088    -     -0.1538 -0.1560      5 matrices
Ind31       0.9249    -      0.1736  0.1769      9 matrices
Ind32       0.0860    -     -0.3139 -0.3174     11 matrices
Ind15       0.6743    -     -0.1667 -0.1714      3 matrices
Ind31       0.4224    -     -0.1765 -0.1788      6 matrices
Ind31       0.7289    -      0.0299  0.0304     10 matrices
Ind31       0.6929    -     -0.0247 -0.0251      7 matrices
Ind31       0.7879    -      0.0217  0.0221      6 matrices
Ind41       0.9078    -      0.1401  0.1428      7 matrices

Locus "Locus10"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.2793    -     -0.1837 -0.1862     11 matrices
Ind31       0.4990    -     -0.1795 -0.1826      5 matrices
Ind31       0.5050    -     -0.1013 -0.1028      8 matrices
Ind32       0.5856    -     -0.1373 -0.1393      5 matrices
Ind15       0.2516    -     -0.3084 -0.3157      8 matrices
Ind31       0.4955    -     -0.1600 -0.1623      5 matrices
Ind31       0.9885    -      0.3333  0.3409      9 matrices
Ind31       0.5820    -     -0.0501 -0.0509      9 matrices
Ind31       0.8749    -      0.1304  0.1329     11 matrices
Ind41       0.4955    -     -0.1600 -0.1623      5 matrices

Locus "Locus11"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.9876    -      0.2771  0.2829      4 matrices
Ind31       0.9585    -      0.2327  0.2375     10 matrices
Ind31       0.9958    -      0.3617  0.3698      3 matrices
Ind32       0.8054    -      0.0802  0.0816     11 matrices
Ind15       0.8966    -     -0.0769 -0.0794      2 matrices
Ind31       0.9078    -      0.1401  0.1428      7 matrices
Ind31       0.9885    -      0.3333  0.3409      9 matrices
Ind31       0.9986    -      0.4595  0.4705      8 matrices
Ind31       1.0000    -      0.7209  0.7415      5 matrices
Ind41       0.8085    -      0.0889  0.0905     14 matrices

Locus "Locus12"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31        - 
Ind31       0.7665    -     -0.0909 -0.0923      4 matrices
Ind31       0.9978    -      0.4369  0.4476      5 matrices
Ind32        - 
Ind15       0.7969    -     -0.1200 -0.1236      3 matrices
Ind31       0.9818    -     -0.0189 -0.0192      2 matrices
Ind31       0.8919    -     -0.0588 -0.0598      3 matrices
Ind31       0.7665    -     -0.0909 -0.0923      4 matrices
Ind31       0.9678    -      0.2045  0.2089      4 matrices
Ind41        - 

Locus "Locus13"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31        - 
Ind31        - 
Ind31        - 
Ind32        - 
Ind15        - 
Ind31        - 
Ind31        - 
Ind31        - 
Ind31        - 
Ind41        - 

Locus "Locus14"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31        - 
Ind31        - 
Ind31       0.9441    -      0.2000  0.2083      4 matrices
Ind32       0.6555    -     -0.0182 -0.0185      9 matrices
Ind15        - 
Ind31       0.9955    -      0.3603  0.3687      3 matrices
Ind31        - 
Ind31       0.7335    -     -0.1064 -0.1082      4 matrices
Ind31       0.8580    -      0.0845  0.0879      4 matrices
Ind41       0.9025    -     -0.0526 -0.0534      3 matrices

Locus "Locus15"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.9935    -      0.3612  0.3696      5 matrices
Ind31       0.7039    -      0.0055  0.0056      9 matrices
Ind31       0.4567    -     -0.1250 -0.1270      8 matrices
Ind32       0.1498    -     -0.2632 -0.2665     13 matrices
Ind15       0.3653    -     -0.2632 -0.2708      6 matrices
Ind31       0.9456    -      0.1892  0.1929      7 matrices
Ind31       0.8562    -      0.1168  0.1190     11 matrices
Ind31       0.4069    -     -0.1222 -0.1239     10 matrices
Ind31       0.7091    -     -0.0169 -0.0172      7 matrices
Ind41       0.3699    -     -0.1281 -0.1300     14 matrices

Locus "Locus16"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.5271    -     -0.0909 -0.0923      8 matrices
Ind31       0.2145    -     -0.2317 -0.2348      9 matrices
Ind31       0.6315    -     -0.0169 -0.0172     11 matrices
Ind32       0.6468    -     -0.0027 -0.0027     13 matrices
Ind15       0.7030    -     -0.0111 -0.0115      6 matrices
Ind31       0.5601    -     -0.1489 -0.1512      5 matrices
Ind31       0.6744    -     -0.0110 -0.0112      8 matrices
Ind31       0.3423    -     -0.1634 -0.1657      9 matrices
Ind31       0.7879    -      0.0217  0.0221      6 matrices
Ind41       0.9009    -      0.1018  0.1037      5 matrices

Locus "Locus17"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.5315    -     -0.1628 -0.1655      5 matrices
Ind31       0.4150    -     -0.1111 -0.1127     12 matrices
Ind31       0.9514    -      0.2235  0.2280     11 matrices
Ind32       0.8911    -      0.1429  0.1458      9 matrices
Ind15       0.6481    -     -0.0370 -0.0383      8 matrices
Ind31       0.9434    -      0.2225  0.2275     13 matrices
Ind31       0.2232    -     -0.2558 -0.2593      7 matrices
Ind31       0.8534    -      0.1176  0.1198     12 matrices
Ind31       0.7726    -      0.0646  0.0657     13 matrices
Ind41       0.5271    -     -0.0909 -0.0923      8 matrices

Locus "Locus18"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.5973    -     -0.1321 -0.1340      5 matrices
Ind31       0.5521    -     -0.0435 -0.0442     14 matrices
Ind31       0.9661    -      0.2551  0.2603     12 matrices
Ind32       0.3976    -     -0.1200 -0.1218     13 matrices
Ind15       0.9689    -      0.2826  0.2986      3 matrices
Ind31       0.1623    -     -0.2857 -0.2894      7 matrices
Ind31       0.6833    -      0.0182  0.0185     15 matrices
Ind31       0.8296    -      0.1045  0.1064     15 matrices
Ind31       0.1890    -     -0.2371 -0.2401     10 matrices
Ind41       0.5050    -     -0.1013 -0.1028      8 matrices

Locus "Locus19"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.1538    -     -0.2529 -0.2560     12 matrices
Ind31       0.8085    -      0.0889  0.0905     14 matrices
Ind31       0.7964    -      0.0835  0.0851     16 matrices
Ind32       0.2083    -     -0.2102 -0.2129     16 matrices
Ind15       0.1791    -     -0.4000 -0.4082      5 matrices
Ind31       0.8279    -      0.1002  0.1021     12 matrices
Ind31       0.7039    -      0.0055  0.0056      9 matrices
Ind31       0.0005    -     -0.6216 -0.6254     13 matrices
Ind31       0.9934    -      0.3684  0.3767     16 matrices
Ind41       0.2702    -     -0.1765 -0.1788     14 matrices

Locus "Locus20"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.4069    -     -0.1222 -0.1239     10 matrices
Ind31       0.9249    -      0.1736  0.1769      9 matrices
Ind31       0.4327    -     -0.1272 -0.1290      8 matrices
Ind32       0.8054    -      0.0802  0.0816     11 matrices
Ind15       0.0512    -     -0.5556 -0.5639      6 matrices
Ind31       0.0721    -     -0.3333 -0.3370      9 matrices
Ind31       0.7726    -      0.0646  0.0657     13 matrices
Ind31       0.5246    -     -0.0638 -0.0648     11 matrices
Ind31       0.6208    -     -0.0543 -0.0552      7 matrices
Ind41       0.9457    -      0.1549  0.1579      5 matrices

Locus "Locus21"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.8544    -      0.0625  0.0636      6 matrices
Ind31       0.7784    -      0.0659  0.0672     11 matrices
Ind31       0.9025    -     -0.0526 -0.0534      3 matrices
Ind32       0.9836    -     -0.0169 -0.0172      2 matrices
Ind15        - 
Ind31       0.6503    -     -0.0588 -0.0603      6 matrices
Ind31       0.9474    -     -0.0370 -0.0377      2 matrices
Ind31       0.8919    -     -0.0588 -0.0598      3 matrices
Ind31       0.6929    -     -0.0247 -0.0251      7 matrices
Ind41       0.9677    -      0.2368  0.2418      6 matrices

Locus "Locus22"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.6747    -     -0.1154 -0.1171      4 matrices
Ind31       0.9508    -     -0.0345 -0.0350      2 matrices
Ind31       0.9818    -     -0.0189 -0.0192      2 matrices
Ind32       0.4512    -     -0.1818 -0.1846      5 matrices
Ind15       0.9962    -      0.4510  0.4739      3 matrices
Ind31       0.9455    -     -0.0385 -0.0391      2 matrices
Ind31       0.9811    -     -0.0196 -0.0200      2 matrices
Ind31        - 
Ind31        - 
Ind41       0.9492    -     -0.0357 -0.0363      2 matrices

Locus "Locus23"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.5246    -     -0.0638 -0.0648     11 matrices
Ind31       0.1890    -     -0.2371 -0.2401     10 matrices
Ind31       0.9134    -      0.1772  0.1806     16 matrices
Ind32       0.1688    -     -0.2541 -0.2573     10 matrices
Ind15       0.8889    -     -0.0833 -0.0862      2 matrices
Ind31       0.4327    -     -0.1272 -0.1290      8 matrices
Ind31       0.9010    -      0.1631  0.1662     14 matrices
Ind31       0.5820    -     -0.0501 -0.0509      9 matrices
Ind31       0.9514    -      0.2235  0.2280     11 matrices
Ind41       0.9934    -      0.3684  0.3767     16 matrices

Locus "Locus24"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.7665    -     -0.0909 -0.0923      4 matrices
Ind31       0.7591    -     -0.0943 -0.0958      4 matrices
Ind31       0.6844    -     -0.1111 -0.1127      4 matrices
Ind32       0.4091    -     -0.1390 -0.1410      8 matrices
Ind15       0.7969    -     -0.1200 -0.1236      3 matrices
Ind31       0.5271    -     -0.0909 -0.0923      8 matrices
Ind31       0.6208    -     -0.0543 -0.0552      7 matrices
Ind31       0.8350    -     -0.0741 -0.0752      3 matrices
Ind31       0.3412    -     -0.2000 -0.2026      6 matrices
Ind41       0.9070    -      0.1064  0.1083      5 matrices

Locus "Locus25"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31        - 
Ind31        - 
Ind31        - 
Ind32        - 
Ind15        - 
Ind31        - 
Ind31        - 
Ind31        - 
Ind31        - 
Ind41        - 

Locus "Locus26"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31        - 
Ind31        - 
Ind31        - 
Ind32        - 
Ind15        - 
Ind31        - 
Ind31        - 
Ind31        - 
Ind31        - 
Ind41       1.0000    -      1.0000  1.0357      2 matrices

Locus "Locus27"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.9999    -      0.5944  0.6106      7 matrices
Ind31        - 
Ind31        - 
Ind32        - 
Ind15        - 
Ind31        - 
Ind31        - 
Ind31        - 
Ind31       0.9836    -     -0.0169 -0.0172      2 matrices
Ind41       0.9952    -      0.3878  0.3966     10 matrices

Locus "Locus28"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       1.0000    -      0.9139  0.9441      8 matrices
Ind31        - 
Ind31        - 
Ind32       1.0000    -      0.6591  0.6772      2 matrices
Ind15        - 
Ind31        - 
Ind31        - 
Ind31       0.9831    -     -0.0175 -0.0178      2 matrices
Ind31        - 
Ind41       0.9635    -      0.2533  0.2589     11 matrices

Locus "Locus29"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31        - 
Ind31       0.9831    -     -0.0175 -0.0178      2 matrices
Ind31        - 
Ind32        - 
Ind15        - 
Ind31        - 
Ind31        - 
Ind31        - 
Ind31        - 
Ind41        - 

Locus "Locus30"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.0000    -     -0.9310 -0.9321     15 matrices
Ind31       0.9876    -      0.2771  0.2829      4 matrices
Ind31       0.9836    -     -0.0169 -0.0172      2 matrices
Ind32       0.1452    -     -0.4776 -0.4882      6 matrices
Ind15       0.8966    -     -0.0769 -0.0794      2 matrices
Ind31       0.9434    -     -0.0400 -0.0407      2 matrices
Ind31        - 
Ind31       0.9508    -     -0.0345 -0.0350      2 matrices
Ind31        - 
Ind41       0.6290    -     -0.1613 -0.1649      4 matrices

Locus "Locus31"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31        - 
Ind31        - 
Ind31        - 
Ind32        - 
Ind15        - 
Ind31        - 
Ind31        - 
Ind31       0.7591    -     -0.0943 -0.0958      4 matrices
Ind31       0.9836    -     -0.0169 -0.0172      2 matrices
Ind41        - 

Locus "Locus32"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.3775    -     -0.1309 -0.1330     14 matrices
Ind31       0.9635    -      0.2533  0.2589     11 matrices
Ind31       0.9744    -      0.2779  0.2837     13 matrices
Ind32       0.6563    -     -0.0425 -0.0432      7 matrices
Ind15       0.6366    -     -0.0633 -0.0657      6 matrices
Ind31       0.6929    -     -0.0247 -0.0251      7 matrices
Ind31       0.9506    -      0.2117  0.2168      6 matrices
Ind31       0.9251    -      0.1811  0.1847     10 matrices
Ind31       0.7289    -      0.0299  0.0304     10 matrices
Ind41       0.7010    -      0.0204  0.0208     11 matrices

Locus "Locus33"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.9836    -     -0.0169 -0.0172      2 matrices
Ind31       0.0309    -     -0.3953 -0.3992     12 matrices
Ind31       0.1132    -     -0.3171 -0.3210      8 matrices
Ind32       0.9941    -      0.3644  0.3726      5 matrices
Ind15       0.8067    -      0.0841  0.0873      7 matrices
Ind31       0.3106    -     -0.1650 -0.1673     11 matrices
Ind31       0.9456    -      0.1892  0.1929      7 matrices
Ind31       0.4452    -     -0.1105 -0.1122     10 matrices
Ind31       0.3423    -     -0.1634 -0.1657      9 matrices
Ind41       0.2532    -     -0.2340 -0.2371      7 matrices

Locus "Locus34"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31        - 
Ind31        - 
Ind31        - 
Ind32        - 
Ind15        - 
Ind31        - 
Ind31        - 
Ind31        - 
Ind31        - 
Ind41        - 

Locus "Locus35"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.8279    -      0.1002  0.1021     12 matrices
Ind31       0.9009    -      0.1018  0.1037      5 matrices
Ind31       0.9421    -      0.1512  0.1542      5 matrices
Ind32       0.7591    -     -0.0943 -0.0958      4 matrices
Ind15        - 
Ind31       0.9150    -      0.1414  0.1460      4 matrices
Ind31       0.8879    -     -0.0612 -0.0623      3 matrices
Ind31       0.5088    -     -0.1538 -0.1560      5 matrices
Ind31       0.7011    -      0.0157  0.0159     10 matrices
Ind41       0.6208    -     -0.0543 -0.0552      7 matrices

Locus "Locus36"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.9876    -      0.2771  0.2829      4 matrices
Ind31       0.5803    -     -0.0732 -0.0744      7 matrices
Ind31       0.9876    -      0.2771  0.2829      4 matrices
Ind32       0.9380    -      0.1472  0.1502      5 matrices
Ind15       0.5936    -     -0.1098 -0.1134      5 matrices
Ind31       0.6278    -     -0.0318 -0.0324      9 matrices
Ind31       0.1132    -     -0.3171 -0.3210      8 matrices
Ind31       0.9078    -      0.1401  0.1428      7 matrices
Ind31       0.8544    -      0.0625  0.0636      6 matrices
Ind41       0.9836    -     -0.0169 -0.0172      2 matrices

Locus "Locus37"
-----------------------------------------
                             Fis estimates
                            ---------------
POP         P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Ind31       0.9508    -     -0.0345 -0.0350      2 matrices
Ind31       0.4452    -     -0.1105 -0.1122     10 matrices
Ind31       0.2034    -     -0.2500 -0.2531      7 matrices
Ind32       0.7302    -     -0.0086 -0.0088      6 matrices
Ind15       0.5395    -     -0.2174 -0.2232      4 matrices
Ind31       0.5642    -     -0.0638 -0.0650      9 matrices
Ind31       0.5579    -     -0.0839 -0.0853      7 matrices
Ind31       0.9707    -      0.2419  0.2468      6 matrices
Ind31       0.9249    -      0.1736  0.1769      9 matrices
Ind41       0.0587    -     -0.3453 -0.3490     13 matrices

==========================================
     Results by population
==========================================


Pop : Ind31
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Locus1      0.4955    -     -0.1600 -0.1623      5 matrices
Locus2      0.6844    -     -0.1111 -0.1127      4 matrices
Locus3      0.9956    -      0.3919  0.4009     12 matrices
Locus4       No information. 
Locus5      0.2793    -     -0.1837 -0.1862     11 matrices
Locus6      0.9025    -     -0.0526 -0.0534      3 matrices
Locus7      0.9025    -     -0.0526 -0.0534      3 matrices
Locus8      0.9661    -      0.2551  0.2603     12 matrices
Locus9       No information. 
Locus10     0.2793    -     -0.1837 -0.1862     11 matrices
Locus11     0.9876    -      0.2771  0.2829      4 matrices
Locus12      No information. 
Locus13      No information. 
Locus14      No information. 
Locus15     0.9935    -      0.3612  0.3696      5 matrices
Locus16     0.5271    -     -0.0909 -0.0923      8 matrices
Locus17     0.5315    -     -0.1628 -0.1655      5 matrices
Locus18     0.5973    -     -0.1321 -0.1340      5 matrices
Locus19     0.1538    -     -0.2529 -0.2560     12 matrices
Locus20     0.4069    -     -0.1222 -0.1239     10 matrices
Locus21     0.8544    -      0.0625  0.0636      6 matrices
Locus22     0.6747    -     -0.1154 -0.1171      4 matrices
Locus23     0.5246    -     -0.0638 -0.0648     11 matrices
Locus24     0.7665    -     -0.0909 -0.0923      4 matrices
Locus25      No information. 
Locus26      No information. 
Locus27     0.9999    -      0.5944  0.6106      7 matrices
Locus28     1.0000    -      0.9139  0.9441      8 matrices
Locus29      No information. 
Locus30     0.0000    -     -0.9310 -0.9321     15 matrices
Locus31      No information. 
Locus32     0.3775    -     -0.1309 -0.1330     14 matrices
Locus33     0.9836    -     -0.0169 -0.0172      2 matrices
Locus34      No information. 
Locus35     0.8279    -      0.1002  0.1021     12 matrices
Locus36     0.9876    -      0.2771  0.2829      4 matrices
Locus37     0.9508    -     -0.0345 -0.0350      2 matrices

Pop : Ind31
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Locus1      0.9825    -     -0.0182 -0.0185      2 matrices
Locus2      0.6644    -     -0.1200 -0.1218      4 matrices
Locus3      0.4862    -     -0.0821 -0.0834     11 matrices
Locus4      0.9519    -      0.2162  0.2207      8 matrices
Locus5      0.9421    -      0.1512  0.1542      5 matrices
Locus6       No information. 
Locus7       No information. 
Locus8      0.2606    -     -0.1837 -0.1862     16 matrices
Locus9      0.5088    -     -0.1538 -0.1560      5 matrices
Locus10     0.4990    -     -0.1795 -0.1826      5 matrices
Locus11     0.9585    -      0.2327  0.2375     10 matrices
Locus12     0.7665    -     -0.0909 -0.0923      4 matrices
Locus13      No information. 
Locus14      No information. 
Locus15     0.7039    -      0.0055  0.0056      9 matrices
Locus16     0.2145    -     -0.2317 -0.2348      9 matrices
Locus17     0.4150    -     -0.1111 -0.1127     12 matrices
Locus18     0.5521    -     -0.0435 -0.0442     14 matrices
Locus19     0.8085    -      0.0889  0.0905     14 matrices
Locus20     0.9249    -      0.1736  0.1769      9 matrices
Locus21     0.7784    -      0.0659  0.0672     11 matrices
Locus22     0.9508    -     -0.0345 -0.0350      2 matrices
Locus23     0.1890    -     -0.2371 -0.2401     10 matrices
Locus24     0.7591    -     -0.0943 -0.0958      4 matrices
Locus25      No information. 
Locus26      No information. 
Locus27      No information. 
Locus28      No information. 
Locus29     0.9831    -     -0.0175 -0.0178      2 matrices
Locus30     0.9876    -      0.2771  0.2829      4 matrices
Locus31      No information. 
Locus32     0.9635    -      0.2533  0.2589     11 matrices
Locus33     0.0309    -     -0.3953 -0.3992     12 matrices
Locus34      No information. 
Locus35     0.9009    -      0.1018  0.1037      5 matrices
Locus36     0.5803    -     -0.0732 -0.0744      7 matrices
Locus37     0.4452    -     -0.1105 -0.1122     10 matrices

Pop : Ind31
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Locus1      0.6844    -     -0.1111 -0.1127      4 matrices
Locus2      0.7116    -     -0.1429 -0.1466      3 matrices
Locus3      0.6327    -     -0.0286 -0.0293     10 matrices
Locus4      0.8402    -     -0.0714 -0.0725      3 matrices
Locus5      0.7039    -      0.0055  0.0056      9 matrices
Locus6       No information. 
Locus7       No information. 
Locus8      0.4778    -     -0.0943 -0.0958     10 matrices
Locus9      0.9249    -      0.1736  0.1769      9 matrices
Locus10     0.5050    -     -0.1013 -0.1028      8 matrices
Locus11     0.9958    -      0.3617  0.3698      3 matrices
Locus12     0.9978    -      0.4369  0.4476      5 matrices
Locus13      No information. 
Locus14     0.9441    -      0.2000  0.2083      4 matrices
Locus15     0.4567    -     -0.1250 -0.1270      8 matrices
Locus16     0.6315    -     -0.0169 -0.0172     11 matrices
Locus17     0.9514    -      0.2235  0.2280     11 matrices
Locus18     0.9661    -      0.2551  0.2603     12 matrices
Locus19     0.7964    -      0.0835  0.0851     16 matrices
Locus20     0.4327    -     -0.1272 -0.1290      8 matrices
Locus21     0.9025    -     -0.0526 -0.0534      3 matrices
Locus22     0.9818    -     -0.0189 -0.0192      2 matrices
Locus23     0.9134    -      0.1772  0.1806     16 matrices
Locus24     0.6844    -     -0.1111 -0.1127      4 matrices
Locus25      No information. 
Locus26      No information. 
Locus27      No information. 
Locus28      No information. 
Locus29      No information. 
Locus30     0.9836    -     -0.0169 -0.0172      2 matrices
Locus31      No information. 
Locus32     0.9744    -      0.2779  0.2837     13 matrices
Locus33     0.1132    -     -0.3171 -0.3210      8 matrices
Locus34      No information. 
Locus35     0.9421    -      0.1512  0.1542      5 matrices
Locus36     0.9876    -      0.2771  0.2829      4 matrices
Locus37     0.2034    -     -0.2500 -0.2531      7 matrices

Pop : Ind32
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Locus1      0.9699    -      0.2077  0.2119      4 matrices
Locus2      0.6753    -     -0.0332 -0.0338      7 matrices
Locus3      0.1816    -     -0.2383 -0.2415     14 matrices
Locus4      0.8293    -     -0.0769 -0.0782      3 matrices
Locus5      0.5732    -     -0.1429 -0.1450      5 matrices
Locus6       No information. 
Locus7       No information. 
Locus8      0.6733    -      0.0000  0.0000     10 matrices
Locus9      0.0860    -     -0.3139 -0.3174     11 matrices
Locus10     0.5856    -     -0.1373 -0.1393      5 matrices
Locus11     0.8054    -      0.0802  0.0816     11 matrices
Locus12      No information. 
Locus13      No information. 
Locus14     0.6555    -     -0.0182 -0.0185      9 matrices
Locus15     0.1498    -     -0.2632 -0.2665     13 matrices
Locus16     0.6468    -     -0.0027 -0.0027     13 matrices
Locus17     0.8911    -      0.1429  0.1458      9 matrices
Locus18     0.3976    -     -0.1200 -0.1218     13 matrices
Locus19     0.2083    -     -0.2102 -0.2129     16 matrices
Locus20     0.8054    -      0.0802  0.0816     11 matrices
Locus21     0.9836    -     -0.0169 -0.0172      2 matrices
Locus22     0.4512    -     -0.1818 -0.1846      5 matrices
Locus23     0.1688    -     -0.2541 -0.2573     10 matrices
Locus24     0.4091    -     -0.1390 -0.1410      8 matrices
Locus25      No information. 
Locus26      No information. 
Locus27      No information. 
Locus28     1.0000    -      0.6591  0.6772      2 matrices
Locus29      No information. 
Locus30     0.1452    -     -0.4776 -0.4882      6 matrices
Locus31      No information. 
Locus32     0.6563    -     -0.0425 -0.0432      7 matrices
Locus33     0.9941    -      0.3644  0.3726      5 matrices
Locus34      No information. 
Locus35     0.7591    -     -0.0943 -0.0958      4 matrices
Locus36     0.9380    -      0.1472  0.1502      5 matrices
Locus37     0.7302    -     -0.0086 -0.0088      6 matrices

Pop : Ind15
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Locus1       No information. 
Locus2       No information. 
Locus3       No information. 
Locus4      0.9689    -      0.2826  0.2986      3 matrices
Locus5      0.8696    -     -0.1000 -0.1039      2 matrices
Locus6      0.8696    -     -0.1000 -0.1039      2 matrices
Locus7      0.7453    -     -0.1579 -0.1636      3 matrices
Locus8      0.5101    -     -0.2381 -0.2448      4 matrices
Locus9      0.6743    -     -0.1667 -0.1714      3 matrices
Locus10     0.2516    -     -0.3084 -0.3157      8 matrices
Locus11     0.8966    -     -0.0769 -0.0794      2 matrices
Locus12     0.7969    -     -0.1200 -0.1236      3 matrices
Locus13      No information. 
Locus14      No information. 
Locus15     0.3653    -     -0.2632 -0.2708      6 matrices
Locus16     0.7030    -     -0.0111 -0.0115      6 matrices
Locus17     0.6481    -     -0.0370 -0.0383      8 matrices
Locus18     0.9689    -      0.2826  0.2986      3 matrices
Locus19     0.1791    -     -0.4000 -0.4082      5 matrices
Locus20     0.0512    -     -0.5556 -0.5639      6 matrices
Locus21      No information. 
Locus22     0.9962    -      0.4510  0.4739      3 matrices
Locus23     0.8889    -     -0.0833 -0.0862      2 matrices
Locus24     0.7969    -     -0.1200 -0.1236      3 matrices
Locus25      No information. 
Locus26      No information. 
Locus27      No information. 
Locus28      No information. 
Locus29      No information. 
Locus30     0.8966    -     -0.0769 -0.0794      2 matrices
Locus31      No information. 
Locus32     0.6366    -     -0.0633 -0.0657      6 matrices
Locus33     0.8067    -      0.0841  0.0873      7 matrices
Locus34      No information. 
Locus35      No information. 
Locus36     0.5936    -     -0.1098 -0.1134      5 matrices
Locus37     0.5395    -     -0.2174 -0.2232      4 matrices

Pop : Ind31
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Locus1      0.8233    -     -0.0800 -0.0813      3 matrices
Locus2       No information. 
Locus3      0.6704    -      0.0110  0.0112     13 matrices
Locus4      0.9508    -     -0.0345 -0.0350      2 matrices
Locus5      0.9789    -      0.2857  0.2918      9 matrices
Locus6       No information. 
Locus7      0.8402    -     -0.0714 -0.0725      3 matrices
Locus8      0.1180    -     -0.2960 -0.2998     13 matrices
Locus9      0.4224    -     -0.1765 -0.1788      6 matrices
Locus10     0.4955    -     -0.1600 -0.1623      5 matrices
Locus11     0.9078    -      0.1401  0.1428      7 matrices
Locus12     0.9818    -     -0.0189 -0.0192      2 matrices
Locus13      No information. 
Locus14     0.9955    -      0.3603  0.3687      3 matrices
Locus15     0.9456    -      0.1892  0.1929      7 matrices
Locus16     0.5601    -     -0.1489 -0.1512      5 matrices
Locus17     0.9434    -      0.2225  0.2275     13 matrices
Locus18     0.1623    -     -0.2857 -0.2894      7 matrices
Locus19     0.8279    -      0.1002  0.1021     12 matrices
Locus20     0.0721    -     -0.3333 -0.3370      9 matrices
Locus21     0.6503    -     -0.0588 -0.0603      6 matrices
Locus22     0.9455    -     -0.0385 -0.0391      2 matrices
Locus23     0.4327    -     -0.1272 -0.1290      8 matrices
Locus24     0.5271    -     -0.0909 -0.0923      8 matrices
Locus25      No information. 
Locus26      No information. 
Locus27      No information. 
Locus28      No information. 
Locus29      No information. 
Locus30     0.9434    -     -0.0400 -0.0407      2 matrices
Locus31      No information. 
Locus32     0.6929    -     -0.0247 -0.0251      7 matrices
Locus33     0.3106    -     -0.1650 -0.1673     11 matrices
Locus34      No information. 
Locus35     0.9150    -      0.1414  0.1460      4 matrices
Locus36     0.6278    -     -0.0318 -0.0324      9 matrices
Locus37     0.5642    -     -0.0638 -0.0650      9 matrices

Pop : Ind31
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Locus1      0.7511    -     -0.0980 -0.0996      4 matrices
Locus2       No information. 
Locus3      0.8581    -      0.1166  0.1192      9 matrices
Locus4      0.9953    -      0.3922  0.4015      8 matrices
Locus5      0.7665    -     -0.0909 -0.0923      4 matrices
Locus6      1.0000    -      0.6591  0.6772      2 matrices
Locus7      0.9958    -      0.3617  0.3698      3 matrices
Locus8      0.9930    -      0.3935  0.4048      9 matrices
Locus9      0.7289    -      0.0299  0.0304     10 matrices
Locus10     0.9885    -      0.3333  0.3409      9 matrices
Locus11     0.9885    -      0.3333  0.3409      9 matrices
Locus12     0.8919    -     -0.0588 -0.0598      3 matrices
Locus13      No information. 
Locus14      No information. 
Locus15     0.8562    -      0.1168  0.1190     11 matrices
Locus16     0.6744    -     -0.0110 -0.0112      8 matrices
Locus17     0.2232    -     -0.2558 -0.2593      7 matrices
Locus18     0.6833    -      0.0182  0.0185     15 matrices
Locus19     0.7039    -      0.0055  0.0056      9 matrices
Locus20     0.7726    -      0.0646  0.0657     13 matrices
Locus21     0.9474    -     -0.0370 -0.0377      2 matrices
Locus22     0.9811    -     -0.0196 -0.0200      2 matrices
Locus23     0.9010    -      0.1631  0.1662     14 matrices
Locus24     0.6208    -     -0.0543 -0.0552      7 matrices
Locus25      No information. 
Locus26      No information. 
Locus27      No information. 
Locus28      No information. 
Locus29      No information. 
Locus30      No information. 
Locus31      No information. 
Locus32     0.9506    -      0.2117  0.2168      6 matrices
Locus33     0.9456    -      0.1892  0.1929      7 matrices
Locus34      No information. 
Locus35     0.8879    -     -0.0612 -0.0623      3 matrices
Locus36     0.1132    -     -0.3171 -0.3210      8 matrices
Locus37     0.5579    -     -0.0839 -0.0853      7 matrices

Pop : Ind31
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Locus1      0.7591    -     -0.0943 -0.0958      4 matrices
Locus2      0.5856    -     -0.1373 -0.1393      5 matrices
Locus3      0.4984    -     -0.0691 -0.0702     14 matrices
Locus4      0.9025    -     -0.0526 -0.0534      3 matrices
Locus5      0.7753    -      0.0151  0.0154      6 matrices
Locus6       No information. 
Locus7       No information. 
Locus8      0.9840    -      0.3103  0.3170     12 matrices
Locus9      0.6929    -     -0.0247 -0.0251      7 matrices
Locus10     0.5820    -     -0.0501 -0.0509      9 matrices
Locus11     0.9986    -      0.4595  0.4705      8 matrices
Locus12     0.7665    -     -0.0909 -0.0923      4 matrices
Locus13      No information. 
Locus14     0.7335    -     -0.1064 -0.1082      4 matrices
Locus15     0.4069    -     -0.1222 -0.1239     10 matrices
Locus16     0.3423    -     -0.1634 -0.1657      9 matrices
Locus17     0.8534    -      0.1176  0.1198     12 matrices
Locus18     0.8296    -      0.1045  0.1064     15 matrices
Locus19     0.0005    -     -0.6216 -0.6254     13 matrices
Locus20     0.5246    -     -0.0638 -0.0648     11 matrices
Locus21     0.8919    -     -0.0588 -0.0598      3 matrices
Locus22      No information. 
Locus23     0.5820    -     -0.0501 -0.0509      9 matrices
Locus24     0.8350    -     -0.0741 -0.0752      3 matrices
Locus25      No information. 
Locus26      No information. 
Locus27      No information. 
Locus28     0.9831    -     -0.0175 -0.0178      2 matrices
Locus29      No information. 
Locus30     0.9508    -     -0.0345 -0.0350      2 matrices
Locus31     0.7591    -     -0.0943 -0.0958      4 matrices
Locus32     0.9251    -      0.1811  0.1847     10 matrices
Locus33     0.4452    -     -0.1105 -0.1122     10 matrices
Locus34      No information. 
Locus35     0.5088    -     -0.1538 -0.1560      5 matrices
Locus36     0.9078    -      0.1401  0.1428      7 matrices
Locus37     0.9707    -      0.2419  0.2468      6 matrices

Pop : Ind31
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Locus1      0.7879    -      0.0217  0.0221      6 matrices
Locus2      1.0000    -      0.6545  0.6828      2 matrices
Locus3      0.9964    -      0.4624  0.4790      7 matrices
Locus4       No information. 
Locus5      0.0405    -     -0.3810 -0.3849      9 matrices
Locus6       No information. 
Locus7      0.9025    -     -0.0526 -0.0534      3 matrices
Locus8      0.6555    -     -0.0182 -0.0185      9 matrices
Locus9      0.7879    -      0.0217  0.0221      6 matrices
Locus10     0.8749    -      0.1304  0.1329     11 matrices
Locus11     1.0000    -      0.7209  0.7415      5 matrices
Locus12     0.9678    -      0.2045  0.2089      4 matrices
Locus13      No information. 
Locus14     0.8580    -      0.0845  0.0879      4 matrices
Locus15     0.7091    -     -0.0169 -0.0172      7 matrices
Locus16     0.7879    -      0.0217  0.0221      6 matrices
Locus17     0.7726    -      0.0646  0.0657     13 matrices
Locus18     0.1890    -     -0.2371 -0.2401     10 matrices
Locus19     0.9934    -      0.3684  0.3767     16 matrices
Locus20     0.6208    -     -0.0543 -0.0552      7 matrices
Locus21     0.6929    -     -0.0247 -0.0251      7 matrices
Locus22      No information. 
Locus23     0.9514    -      0.2235  0.2280     11 matrices
Locus24     0.3412    -     -0.2000 -0.2026      6 matrices
Locus25      No information. 
Locus26      No information. 
Locus27     0.9836    -     -0.0169 -0.0172      2 matrices
Locus28      No information. 
Locus29      No information. 
Locus30      No information. 
Locus31     0.9836    -     -0.0169 -0.0172      2 matrices
Locus32     0.7289    -      0.0299  0.0304     10 matrices
Locus33     0.3423    -     -0.1634 -0.1657      9 matrices
Locus34      No information. 
Locus35     0.7011    -      0.0157  0.0159     10 matrices
Locus36     0.8544    -      0.0625  0.0636      6 matrices
Locus37     0.9249    -      0.1736  0.1769      9 matrices

Pop : Ind41
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Locus1      0.5732    -     -0.1429 -0.1450      5 matrices
Locus2      0.8453    -      0.0569  0.0579      6 matrices
Locus3      0.7367    -      0.0447  0.0455     13 matrices
Locus4      0.9859    -      0.2996  0.3060      6 matrices
Locus5      0.8402    -     -0.0714 -0.0725      3 matrices
Locus6      0.9455    -     -0.0385 -0.0391      2 matrices
Locus7      0.9474    -     -0.0370 -0.0377      2 matrices
Locus8      0.9753    -      0.2771  0.2829     11 matrices
Locus9      0.9078    -      0.1401  0.1428      7 matrices
Locus10     0.4955    -     -0.1600 -0.1623      5 matrices
Locus11     0.8085    -      0.0889  0.0905     14 matrices
Locus12      No information. 
Locus13      No information. 
Locus14     0.9025    -     -0.0526 -0.0534      3 matrices
Locus15     0.3699    -     -0.1281 -0.1300     14 matrices
Locus16     0.9009    -      0.1018  0.1037      5 matrices
Locus17     0.5271    -     -0.0909 -0.0923      8 matrices
Locus18     0.5050    -     -0.1013 -0.1028      8 matrices
Locus19     0.2702    -     -0.1765 -0.1788     14 matrices
Locus20     0.9457    -      0.1549  0.1579      5 matrices
Locus21     0.9677    -      0.2368  0.2418      6 matrices
Locus22     0.9492    -     -0.0357 -0.0363      2 matrices
Locus23     0.9934    -      0.3684  0.3767     16 matrices
Locus24     0.9070    -      0.1064  0.1083      5 matrices
Locus25      No information. 
Locus26     1.0000    -      1.0000  1.0357      2 matrices
Locus27     0.9952    -      0.3878  0.3966     10 matrices
Locus28     0.9635    -      0.2533  0.2589     11 matrices
Locus29      No information. 
Locus30     0.6290    -     -0.1613 -0.1649      4 matrices
Locus31      No information. 
Locus32     0.7010    -      0.0204  0.0208     11 matrices
Locus33     0.2532    -     -0.2340 -0.2371      7 matrices
Locus34      No information. 
Locus35     0.6208    -     -0.0543 -0.0552      7 matrices
Locus36     0.9836    -     -0.0169 -0.0172      2 matrices
Locus37     0.0587    -     -0.3453 -0.3490     13 matrices

Normal ending
