# Designed to look similar to the bioperl design.

# At present, these are all hand written.  I would like to have
# autogenerated parsers in the futures, esp. with the ability to parse
# only subsets of the data, and to support event generated parsers.

# Note that once a parser is given an input string, it is free to read
# as much of the data as it wants to read, unless otherwise mentioned.

__all__ = [
    'FASTA'
    ]
