Some header
>gi|3298468|dbj|BAA31520.1| SAMIPF
;Some comment here
GGHVNPAVTFGAFVGGNITLLRGIVYIIAQLLGSTVACLLLKFVTNDMAVGVFSLSAGVGVTNALVFEIV
;Another comment here
MTFGLVYTVYATAIDPKKGSLGTIAPIAIGFIVGANI
;One more comment
