all: doc
.PHONY: all doc clean

doc:
	- pdflatex Tutorial
	- pdflatex Tutorial
	- pdflatex Tutorial

clean:
	- rm -f Doc/Tutorial.ps Doc/Tutorial.log Doc/Tutorial.dvi \
	Doc/Tutorial.aux
	- rm -rf Doc/api
