#Work in progress, not ready for reviewing


from Bio.SeqAnalysis.SeqAnalyzer import SeqAnalyzer
import unittest
from Bio import SeqIO
#cant create objects

data = {
    'czlowiek': 'MGKKRAVGAQALACFECERCKSDNEQYCTNDHVLTMWTPYKDG',
    'pies': 'MSVKPSKKKKRSKVKKKISFDFSDDDDSEIGVSFR',
    'maciek': 'MRALAYFGKGNIRFTNHLKEPHIVAPDELVIDIEWCGICGTDLHEYTDGPIFFPEDGHTHEISHNPLPQAMGHEMAGTVLEVGPGVKNLKVGDKVVVEPTGTCRDYNICSYLGLCGAGVQSGGFAERVVMNESHCYKVPDFVPLDVAALIQPLAVCWH',
    'kubiks': 'IFFPEDGHTHEISHNPLPQAMGHEMAGTVLEVGPGVKNLKVGDKVVVEPTGTCR',
    'janeks': 'MKCTIPEQQKVILIDEIGGYDVIKYEDYPVPSISEEELLIKNKYTGVNYIESYFRKGIYPCEKPYVLGREASGTVVAKGKGVTNFEVGDQVAYISNSTFAQYSKISSQGPVMKLPKGTSDEELKLYAAVLLFAAAGGVGLILNQLLKMKGAHTIAVA',
    'BigKacper_22cm': 'KVGSKCHTGVKIGDRVGVGAQALACFECERCKSDNEQYCTNDHVLTMWTPYKDGYISQGGFASHVRLHEHFAIQIPENIPSPLAAPLLCGGITVFSPLLRNGCGPGKRVGIVGIGGIGHMGILLAKAMGAEVYAFSRGHSK'
}

analyzer = Bio.SeqAnalysis.SeqAnalyzer(records)
reults = analyzer.results()

SeqAnalyzer = SeqAnalyzer(input_data)
