#!/usr/bin/env python

# This file generated by a program. do not edit.
import Bio.EUtils.POM

#     
#                 This is the Current DTD for Entrez ePost
# $Id: ePost_020511.py,v 1.3 2007-07-21 14:55:33 mdehoon Exp $
# 
# 
#  ================================================================= 
class QueryKey(Bio.EUtils.POM.ElementNode):
	CONTENTMODEL = Bio.EUtils.POM.ContentModel(('', [('#PCDATA', '')], ''))


#  \d+ 
class WebEnv(Bio.EUtils.POM.ElementNode):
	CONTENTMODEL = Bio.EUtils.POM.ContentModel(('', [('#PCDATA', '')], ''))


#  \S+ 
class ERROR(Bio.EUtils.POM.ElementNode):
	CONTENTMODEL = Bio.EUtils.POM.ContentModel(('', [('#PCDATA', '')], ''))


#  .+ 
#  Added by Andrew Dalke (dalke@dalkescientific.com) to support
#      the new InvalidIdList interface 
class Id(Bio.EUtils.POM.ElementNode):
	CONTENTMODEL = Bio.EUtils.POM.ContentModel(('', [('#PCDATA', '')], ''))


#  .+ 
class InvalidIdList(Bio.EUtils.POM.ElementNode):
	CONTENTMODEL = Bio.EUtils.POM.ContentModel(('', [(u'Id', u'*')], ''))


class ePostResult(Bio.EUtils.POM.ElementNode):
	CONTENTMODEL = Bio.EUtils.POM.ContentModel((u'|', [(u',', [(u'QueryKey', ''), (u'InvalidIdList', u'?'), (u'WebEnv', '')], ''), (u'ERROR', '')], ''))

