>P1;HLA:HLA00401
HLA:HLA00401 Cw*0102, 366 bases, BCB2E2 checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMK YFFTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRNLRGYYN QSEAGSHTLQ WMCGCDLGPD GRLLRGYDQY AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQWDGEDQTQ
 DTELVETRPA GDGTFQKWAA VMVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00402
HLA:HLA00402 Cw*0103, 366 bases, 4F7299A9 checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMK YFFTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRNLRGYYN QSEAGSHTLQ WMCGCDLGPD GRLLRGYNQF AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQWDGEDQTQ
 DTELVETRPA GDGTFQKWAA VMVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA01075
HLA:HLA01075 Cw*0104, 366 bases, 7A09938E checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMK YFFTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRNLRGYYN QSEAGSHTLQ WMCGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQW RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA01434
HLA:HLA01434 Cw*0105, 181 bases, BE2C33E6 checksum.
 SHSMKYFFTS VSRPGRGEPR FISVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVSLRNL RGYYNQSEAG SHTLQRMSGC
 DLGPDGRLLR GYDQYAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQRRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00404
HLA:HLA00404 Cw*02021, 366 bases, B4E410F1 checksum.
 MRVMAPRTLL LLLSGALALT ETWACSHSMR YFYTAVSRPS RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 NLRKLRGYYN QSEAGSHTLQ RMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQW RAYLEGECVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPTEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00405
HLA:HLA00405 Cw*02022, 366 bases, B6CE347D checksum.
 MRVMAPRTLL LLLSGALALT ETWACSHSMR YFYTAVSRPS RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 NLRKLRGYYN QSEAGSHTLQ RMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQW RAYLEGECVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPTEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00406
HLA:HLA00406 Cw*02023, 181 bases, 160F707B checksum.
 SHSMRYFYTA VSRPSRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVNLRKL RGYYNQSEAG SHTLQRMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQWRAYLE GECVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00407
HLA:HLA00407 Cw*02024, 338 bases, 4B6B9A0F checksum.
 MRVMAPRTLL LLLSGALALT ETWACSHSMR YFYTAVSRPS RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 NLRKLRGYYN QSEAGSHTLQ RMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQW RAYLEGECVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSS*

>P1;HLA:HLA01471
HLA:HLA01471 Cw*02025, 181 bases, 160F707B checksum.
 SHSMRYFYTA VSRPSRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVNLRKL RGYYNQSEAG SHTLQRMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQWRAYLE GECVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00408
HLA:HLA00408 Cw*0203, 181 bases, 160F707B checksum.
 SHSMRYFYTA VSRPSRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVNLRKL RGYYNQSEAG SHTLQRMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 VAEQLRAYLE GECVEWLRRY LENGKETLQR A*

>P1;HLA:HLA01344
HLA:HLA01344 Cw*0204, 181 bases, F9EDBC19 checksum.
 SHSMRCFYTA VSRPSRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVNLRKL RGYYNQSEAG SHTLQRMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQWRAYLE GECVEWLRRY LENGKETLQR A*

>P1;HLA:HLA01472
HLA:HLA01472 Cw*0205, 181 bases, B2B457B7 checksum.
 SHSMRYFYTA VSRPSRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVNLRKL RGYYNQSEAG SHTLQWMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQWRAYLE GECVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00410
HLA:HLA00410 Cw*0302, 366 bases, 2A0780B4 checksum.
 MRVMAPRTLI LLLSGALALT ETWAGSHSMR YFYTAVSRPG RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRNLRGYYN QSEAGSHILQ RMYGCDVGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQL RAYLEGLCVE WLRRYLKNGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQWDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00411
HLA:HLA00411 Cw*03031, 366 bases, 8092EBD0 checksum.
 MRVMAPRTLI LLLSGALALT ETWAGSHSMR YFYTAVSRPG RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRNLRGYYN QSEARSHIIQ RMYGCDVGPD GRLLRGYDQY AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQL RAYLEGLCVE WLRRYLKNGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQWDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00412
HLA:HLA00412 Cw*03032, 366 bases, 1F851F96 checksum.
 MRVMAPRTLI LLLSGALALT ETWAGSHSMR YFYTAVSRPG RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRNLRGYYN QSEARSHIIQ RMYGCDVGPD GRLLRGYDQY AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQL RAYLEGLCVE WLRRYLKNGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQWDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA01355
HLA:HLA01355 Cw*03033, 181 bases, 259B2630 checksum.
 SHSMRYFYTA VSRPGRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVSLRNL RGYYNQSEAR SHIIQRMYGC
 DVGPDGRLLR GYDQYAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQLRAYLE GLCVEWLRRY LKNGKETLQR A*

>P1;HLA:HLA00413
HLA:HLA00413 Cw*03041, 366 bases, FB00725B checksum.
 MRVMAPRTLI LLLSGALALT ETWAGSHSMR YFYTAVSRPG RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRNLRGYYN QSEAGSHIIQ RMYGCDVGPD GRLLRGYDQY AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQL RAYLEGLCVE WLRRYLKNGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQWDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00414
HLA:HLA00414 Cw*03042, 181 bases, EE7A20BE checksum.
 SHSMRYFYTA VSRPGRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVSLRNL RGYYNQSEAG SHIIQRMYGC
 DVGPDGRLLR GYDQYAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQLRAYLE GLCVEWLRRY LKNGKETLQR A*

>P1;HLA:HLA00415
HLA:HLA00415 Cw*0305, 181 bases, 861EE214 checksum.
 SHSMRYFYTA VSRPGRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVSLRNL RGYYNQSEAG SHTLQSMYGC
 DVGPDGRLLR GYDQYAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQLRAYLE GLCVEWLRRY LKNGKETLQR A*

>P1;HLA:HLA00416
HLA:HLA00416 Cw*0306, 181 bases, EE7A20BE checksum.
 SHSMRYFYTA VSRPGRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVSLRNL RGYYNQSEAG SHIIQRMYGC
 DVGPDGRLLR GYVQYAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQLRAYLE GLCVEWLRRY LKNGKETLQR A*

>P1;HLA:HLA00417
HLA:HLA00417 Cw*0307, 181 bases, BA3BB2CD checksum.
 SHSMRYFYTA VSRPGRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVNLRKL RGYYNQSEAG SHIIQRMYGC
 DVGPDGRLLR GYDQYAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQLRAYLE GLCVEWLRRY LKNGKETLQR A*

>P1;HLA:HLA00418
HLA:HLA00418 Cw*0308, 338 bases, 447DEE8E checksum.
 MRVMAPRTLI LLLSGALALT ETWAGSHSMR YFYTAVSRPG RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQN YKRQAQTDRV
 SLRNLRGYYN QSEAGSHIIQ RMYGCDVGPD GRLLRGYDQY AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQL RAYLEGLCVE WLRRYLKNGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQWDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSS*

>P1;HLA:HLA00419
HLA:HLA00419 Cw*0309, 181 bases, 128B64EF checksum.
 SHSMRYFYTA VSRPGRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVSLRNL RGYYNQSEAG SHIIQRMYGC
 DLGPDGRLLR GYDQYAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQLRAYLE GLCVEWLRRY LKNGKETLQR A*

>P1;HLA:HLA01076
HLA:HLA01076 Cw*0310, 181 bases, EE7A20BE checksum.
 SHSMRYFYTA VSRPGRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVSLRKL RGYYNQSEAG SHIIQRMYGC
 DVGPDGRLLR GYDQYAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQLRAYLE GLCVEWLRRY LKNGKETLQR A*

>P1;HLA:HLA01077
HLA:HLA01077 Cw*0311, 181 bases, FF944BC4 checksum.
 SHSMRYFYTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVSLRNL RGYYNQSEAR SHIIQRMYGC
 DVGPDGRLLR GYDQYAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQLRAYLE GLCVEWLRRY LKNGKETLQR A*

>P1;HLA:HLA01125
HLA:HLA01125 Cw*0312, 181 bases, 259B2630 checksum.
 SHSMRYFYTA VSRPGRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVSLRNL RGYYNQSEAR SHIIQRMYGC
 DVGPDGRLLR GYDQLAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQLRAYLE GLCVEWLRRY LKNGKETLQR A*

>P1;HLA:HLA01412
HLA:HLA01412 Cw*0313, 366 bases, 8B301C1F checksum.
 MRVMAPRTLI LLLSGALALT ETWAGSHSMR YFYTAVSRPG RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRNLRGYYN QSEARSHTLQ RMYGCDVGPD GRLLRGYDQY AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQL RAYLEGLCVE WLRRYLKNGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQWDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA01425
HLA:HLA01425 Cw*0314, 181 bases, 2AF2B420 checksum.
 SHSMRYFYTA VSRPGRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVSLRNL RGYYNQSEAG SHIIQRMYGC
 DVGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKLEAAR
 AAEQLRAYLE GTCVEWLRRY LKNGKETLQR A*

>P1;HLA:HLA00420
HLA:HLA00420 Cw*0401101, 366 bases, DCCDAAC4 checksum.
 MRVMAPRTLI LLLSGALALT ETWAGSHSMR YFSTSVSWPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRGE PREPWVEQEG PEYWDRETQK YKRQAQADRV
 NLRKLRGYYN QSEDGSHTLQ RMFGCDLGPD GRLLRGYNQF AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQWDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWKP
 SSQPTIPIVG IVAGLAVLAV LAVLGAMVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA01328
HLA:HLA01328 Cw*0401102, 366 bases, 507CC384 checksum.
 MRVMAPRTLI LLLSGALALT ETWAGSHSMR YFSTSVSWPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRGE PREPWVEQEG PEYWDRETQK YKRQAQADRV
 NLRKLRGYYN QSEDGSHTLQ RMFGCDLGPD GRLLRGYNQF AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQWDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWKP
 SSQPTIPIVG IVAGLAVLAV LAVLGAMVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00421
HLA:HLA00421 Cw*04012, 181 bases, B68D55ED checksum.
 SHSMRYFSTS VSWPGRGEPR FIAVGYVDDT QFVRFDSDAA SPRGEPREPW
 VEQEGPEYWD RETQKYKRQA QADRVNLRKL RGYYNQSEDG SHTLQRMFGC
 DLGPDGRLLR GYNQFAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQRRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00423
HLA:HLA00423 Cw*0403, 366 bases, E3D3474D checksum.
 MRVMAPRTLI LLLSGALALT ETWAGSHSMR YFYTAVSRPS RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQADRV
 NLRKLRGYYN QSEDGSHTLQ RMFGCDLGPD GRLLRGYNQF AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQWDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWKP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00424
HLA:HLA00424 Cw*0404, 181 bases, B68D55ED checksum.
 SHSMRYFSTS VSWPGRGEPR FIAVGYVDDT QFVRFDSDAA SPRGEPREPW
 VEQEGPEYWD RETQKYKRQA QADRVNLRKL RGYYNQSEDG SHTLQRMFGC
 DLGPDGRLLR GYNQFAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQLRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00425
HLA:HLA00425 Cw*0405, 181 bases, B68D55ED checksum.
 SHSMRYFSTS VSWPGRGEPR FIAVGYLDDT QFVRFDSDAA SPRGEPREPW
 VEQEGPEYWD RETQKYKRQA QADRVNLRKL RGYYNQSEDG SHTLQRMFGC
 DLGPDGRLLR GYNQFAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQRRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00426
HLA:HLA00426 Cw*0406, 181 bases, 17BC0B7C checksum.
 SHSMRYFYTA VSRPSRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVNLRKL RGYYNQSEDG SHTLQRMFGC
 DLGPDGRLLR GYNQFAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQLRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA01078
HLA:HLA01078 Cw*0407, 181 bases, A34ABAC3 checksum.
 SHSMRYFSTS VSWPGRGEPR FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVNLRKL RGYYNQSEDG SHTLQRMFGC
 DLGPDGRLLR GYNQFAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQRRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA01311
HLA:HLA01311 Cw*0408, 181 bases, 9A7AEF2E checksum.
 SHSMRYFSTS VSWPGRGEPR FIAVGYVDDT QFVRFDSDAA SPRGEPREPW
 VEQEGPEYWD RETQKYKRQA QADRVNLRKL RGYYNQSEDG SHTLQRMFGC
 DLGPDGRLLR GYNQFAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQRRAYLE GLCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA01451
HLA:HLA01451 Cw*0409N, 398 bases, 9EB029FE checksum.
 MRVMAPRTLI LLLSGALALT ETWAGSHSMR YFSTSVSWPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRGE PREPWVEQEG PEYWDRETQK YKRQAQADRV
 NLRKLRGYYN QSEDGSHTLQ RMFGCDLGPD GRLLRGYNQF AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQWDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWKP
 SSQPTIPIVG IVAGLAVLAV LAVLGAMVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKPETAA CVGLRCRISS HLSFVTSRAS GISFCKGI*

>P1;HLA:HLA00427
HLA:HLA00427 Cw*0501, 366 bases, 2C55FA5F checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVQF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 NLRKLRGYYN QSEAGSHTLQ RMYGCDLGPD GRLLRGYNQF AYDGKDYIAL
 NEDLRSWTAA DKAAQITQRK WEAAREAEQR RAYLEGTCVE WLRRYLENGK
 KTLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWGP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00428
HLA:HLA00428 Cw*0502, 181 bases, 52542BB5 checksum.
 SHSMRYFYTA VSRPGRGEPR FIAVGYVDDT QFVQFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVNLRKL RGYYNQSEAG SHTLQRMYGC
 DLGPDGRLLR GYNQFAYDGK DYIALNEDLR SWTAADKAAQ ITQRKWEAAR
 EAEQRRAYLE GMCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA01169
HLA:HLA01169 Cw*0503, 366 bases, 38075173 checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVQF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 NLRKLRGYYN QSEAGSHTLQ RMYGCDLGPD GRLLRGYNQF AYDGKDYIAL
 NEDLRSWTAA DKAAQITQRK WEAAREAEQR RAYLEGTCVE WLRRYLENGK
 KTLQRADPPK THVTHHPISD HEVTLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWGP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA01174
HLA:HLA01174 Cw*0504, 181 bases, E4B58B86 checksum.
 SHSMRYFYTA VSRPGRGEPR FIAVGYVDDT QFVQFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVNLRKL RGYYNQSEAG SHTLQRMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADKAAQ ITQRKWEAAR
 EAEQRRAYLE GTCVEWLRRY LENGKKTLQR A*

>P1;HLA:HLA00430
HLA:HLA00430 Cw*0602, 366 bases, B1AFE4D6 checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFDTAVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQADRV
 NLRKLRGYYN QSEDGSHTLQ WMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQW RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00431
HLA:HLA00431 Cw*0603, 181 bases, D1FAF54F checksum.
 SHSMRYFYTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVNLRKL RGYYNQSEDG SHTLQWMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQWRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00432
HLA:HLA00432 Cw*0604, 181 bases, D6FBC265 checksum.
 SHSMRYFDTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVNLRKL RGYYNQSEDG SHTLQWMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQLRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00991
HLA:HLA00991 Cw*0605, 181 bases, 53D2F1AF checksum.
 SHSMRYFDTA VSRPGRGEPR FISVGYVDDT QFVQFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVNLRKL RGYYNQSEDG SHTLQWMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQRRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA01258
HLA:HLA01258 Cw*0606, 313 bases, E74DC724 checksum.
 SHSMRYFDTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVNLRKL RGYYNQSEDG SHTLQWMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQRRAYLE GTCVEWLRRY LENGKETLQR AEHPKTHVTH HPVSDHEATL
 RCWALGFYPA EITLTWQRDG EDQTQDTELV ETRPAGDGTF QKWAAVVVPS
 GEEQRYTCHV QHEGLPEPLT LRWEPSSQPT IPIVGIVAGL AVLAVLAVLG
 AVMAVVMCRR KSS*

>P1;HLA:HLA01301
HLA:HLA01301 Cw*0607, 181 bases, D6FBC265 checksum.
 SHSMRYFDTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEKEGPEYWD RETQKYKRQA QADRVNLRKL RGYYNQSEDG SHTLQWMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQWRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00433
HLA:HLA00433 Cw*07011, 366 bases, B9B841B checksum.
 MRVMAPRALL LLLSGGLALT ETWACSHSMR YFDTAVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQN YKRQAQADRV
 SLRNLRGYYN QSEDGSHTLQ RMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK LEAARAAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRAEPPK THVTHHPLSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YTCHMQHEGL QEPLTLSWEP
 SSQPTIPIMG IVAGLAVLVV LAVLGAVVTA MMCRRKSSGG KGGSCSQAAC
 SNSAQGSDES LITCKA*

>P1;HLA:HLA00992
HLA:HLA00992 Cw*07012, 338 bases, ABD990B checksum.
 MRVMAPRALL LLLSGGLALT ETWACSHSMR YFDTAVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQN YKRQAQADRV
 SLRNLRGYYN QSEDGSHTLQ RMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK LEAARAAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRAEPPK THVTHHPLSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YTCHMQHEGL QEPLTLSWEP
 SSQPTIPIMG IVAGLAVLVV LAVLGAVVTA MMCRRKSS*

>P1;HLA:HLA00434
HLA:HLA00434 Cw*0702101, 366 bases, 44630DCA checksum.
 MRVMAPRALL LLLSGGLALT ETWACSHSMR YFDTAVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQADRV
 SLRNLRGYYN QSEDGSHTLQ RMSGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK LEAARAAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRAEPPK THVTHHPLSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YTCHMQHEGL QEPLTLSWEP
 SSQPTIPIMG IVAGLAVLVV LAVLGAVVTA MMCRRKSSGG KGGSCSQAAC
 SNSAQGSDES LITCKA*

>P1;HLA:HLA01326
HLA:HLA01326 Cw*0702102, 366 bases, 33987C4E checksum.
 MRVMAPRALL LLLSGGLALT ETWACSHSMR YFDTAVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQADRV
 SLRNLRGYYN QSEDGSHTLQ RMSGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK LEAARAAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRAEPPK THVTHHPLSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YTCHMQHEGL QEPLTLSWEP
 SSQPTIPIMG IVAGLAVLVV LAVLGAVVTA MMCRRKSSGG KGGSCSQAAC
 SNSAQGSDES LITCKA*

>P1;HLA:HLA00435
HLA:HLA00435 Cw*0703, 342 bases, B2C1A049 checksum.
 CSHSMRYFDT AVSRPGAGEP RFISVGYVDD TQFVRFDSDA ASPRGEPRAP
 WVEQEGPEYW DRETQKYKRQ AQADRVSLRN LRGYYNQSED GSHTLQRMSG
 CDLGPDGRLL RGYDQSAYDG KDYIALNEDL RSWTAADTAA QITQRKWEAA
 RAAEQLRAYL EGLCVEWLRR YLENGKETLQ RAEPPKTHVT HHPLSDHEAT
 LRCWALGFYP AEITLTWQRD GEDQTQDTEL VETRPAGDGT FQKWAAVVVP
 SGQEQRYTCH MQHEGLQEPL TLSWEPSSQP TIPIMGIVAG LAVLVVLAVL
 GAVVTAMMCR RKSSGGKGGS CSQAACSNSA QGSDESLITC KA*

>P1;HLA:HLA00436
HLA:HLA00436 Cw*0704, 366 bases, 35E7E6B3 checksum.
 MRVMAPRALL LLLSGGLALT ETWACSHSMR YFDTAVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQADRV
 SLRNLRGYYN QSEDGSHTFQ RMYGCDLGPD GRLLRGYDQF AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK LEAARAAEQD RAYLEGTCVE WLRRYLENGK
 KTLQRAEPPK THVTHHPLSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YTCHMQHEGL QEPLTLSWEP
 SSQPTIPIMG IVAGLAVLVV LAVLGAVVTA MMCRRKSSGG KGGSCSQAAC
 SNSAQGSDES LITCKA*

>P1;HLA:HLA00437
HLA:HLA00437 Cw*0705, 181 bases, 8C526DC0 checksum.
 SHSMRYFDTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVSLRNL RGYYNQSEDG SHTLQNMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKLEAAR
 AAEQLRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00438
HLA:HLA00438 Cw*0706, 366 bases, E254CD98 checksum.
 MRVMAPRALL LLLSGGLALT ETWACSHSMR YFDTAVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQN YKRQAQADRV
 SLRNLRGYYN QSEDGSHTLQ RMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK LEAARAAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRAEPPK THVTHHPLSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YTCHMQHEGL QEPLTLSWEP
 SSQPTIPIMG IVAGLAVLVV LAVLGAVVTA KMCRRKSSGG KGGSCSQVAC
 SNSAQGSDES LITCKA*

>P1;HLA:HLA00439
HLA:HLA00439 Cw*0707, 181 bases, 9A3FCBF4 checksum.
 SHSMRYFDTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQNYKRQA QADRVNLRKL RGYYNQSEAG SHTLQRMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKLEAAR
 AAEQLRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00440
HLA:HLA00440 Cw*0708, 181 bases, 768CED8C checksum.
 SHSMRYFDTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVSLRNL RGYYNQSEDG SHTLQRMFGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKLEAAR
 AAEQLRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00441
HLA:HLA00441 Cw*0709, 181 bases, 9A3FCBF4 checksum.
 SHSMRYFDTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQNYKRQA QADRVNLRKL RGYYNQSEDG SHTLQRMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKLEAAR
 AAEQLRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00442
HLA:HLA00442 Cw*0710, 181 bases, 89CF2EF7 checksum.
 SHSMRYFDTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVSLRNL RGYYNQSEDG SHIIQRMSGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKLEAAR
 AAEQLRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00443
HLA:HLA00443 Cw*0711, 366 bases, D856C253 checksum.
 MRVMAPRALL LLLSGGLALT ETWACSHSMR YFDTAVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQADRV
 SLRNLRGYYN QSEDGSHTFQ RMYGCDLGPD GRLLRGYDQF AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK LEAARAAEQD RAYLEGTCVE WLRRYLENGK
 KTLQRAEPPK THVTHHPLSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YTCHMQHEGL QEPLTLSWEP
 SSQPTIPIMG IVAGLAVLVV LAVLGAVVTA MMCRRKSSGG KGGSCSQAAC
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00444
HLA:HLA00444 Cw*0712, 181 bases, CD41702C checksum.
 SHSMRYFDTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVSLRNL RGYYNQSEDG SHTFQRMYGC
 DLGPDGRLLR GYDQFAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 AAEQDRAYLE GTCVEWLRRY LENGKKTLQR A*

>P1;HLA:HLA01079
HLA:HLA01079 Cw*0713, 181 bases, 1BB91B4B checksum.
 SHSMRYFDTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVSLRNL RGYYNQSEDG SHTLQRMSGC
 DLGPDGRLLR GYDQFAYDGK DYIALNEDLR SWTAADTAAQ ITQRKLEAAR
 AAEQLRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA01080
HLA:HLA01080 Cw*0714, 181 bases, CE7E5987 checksum.
 SHSMRYFDTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVSLRNL RGYYNQSEDG SHTLQRMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKLEAAR
 AAEQLRAYLE GTCVEWLRRY LENGKETLQR T*

>P1;HLA:HLA01408
HLA:HLA01408 Cw*0715, 181 bases, 14F845C9 checksum.
 SHSMRYFDTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVSLRNL RGYYNQSEDG SHTLQRMSGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKLEAAR
 AAEQLRAYLE GECVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00445
HLA:HLA00445 Cw*0801, 366 bases, EEE87E3D checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVQF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRNLRGYYN QSEAGSHTLQ RMYGCDLGPD GRLLRGYNQF AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAARTAEQL RAYLEGTCVE WLRRYLENGK
 KTLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWGP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00446
HLA:HLA00446 Cw*0802, 366 bases, 712B8A1E checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVQF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRNLRGYYN QSEAGSHTLQ RMYGCDLGPD GRLLRGYNQF AYDGKDYIAL
 NEDLRSWTAA DKAAQITQRK WEAAREAEQR RAYLEGTCVE WLRRYLENGK
 KTLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWGP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00447
HLA:HLA00447 Cw*0803, 366 bases, EEE87E3D checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVQF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRNLRGYYN QSEAGSHTLQ RMYGCDLGPD GRLLRGYNQF AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAARTAEQL RAYLEGTCVE WLRRYLENRK
 KTLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWGP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00448
HLA:HLA00448 Cw*0804, 181 bases, B0F419F5 checksum.
 SHSMRYFYTA VSRPGRGEPR FIAVGYVDDT QFVQFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVSLRNL RGYYNQSEAG SHTLQRMYGC
 DLGPDGRLLR GYNQFAYDGK DYIALNEDLR SWTAADKAAQ ITQRKWEAAR
 EAEQLRAYLE GTCVEWLRRY LENGKKTLQR A*

>P1;HLA:HLA00449
HLA:HLA00449 Cw*0805, 181 bases, 6F4887B checksum.
 SHSMRYFYTA VSRPGRGEPR FIAVGYVDDT QFVQFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVSLRNL RGYYNQSEAG SHTLQRMYGC
 DLGPDGRLLR GYNQFAYDGK DYIALNEDLR SWTAADKAAQ ITQRKWEAAR
 EAEQRRAYLE GTCVEWLRRY LENGKKTLQR A*

>P1;HLA:HLA00450
HLA:HLA00450 Cw*0806, 181 bases, 1D058990 checksum.
 SHSMRYFYTA VSRPGRGEPR FIAVGYVDDT QFVQFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVSLRNL RGYYNQSEAG SHTLQRMYGC
 DLGPDGRLLR GYNQFAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 TAEQLRAYLE GACVEWLRRY LENRKKTLQR A*

>P1;HLA:HLA01136
HLA:HLA01136 Cw*0807, 181 bases, 588B37A8 checksum.
 SHSMRYFYTA VSRPGRGEPR FIAVGYVDDT QFVQFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVSLRNL RGYYNQSEAG SHTLQRMYGC
 DLGPDGRLLR GYNQFAYDGK DYIALNEDLR SWTAADKAAQ ITQRKLEAAR
 EAEQRRAYLE GTCVEWLRRY LENGKKTLQR A*

>P1;HLA:HLA01238
HLA:HLA01238 Cw*0808, 181 bases, 4AE6EEE3 checksum.
 SHSMRYFYTA VSRPGRGEPR FIAVGYVDDT QFVQFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVSLRNL RGYYNQSEAG SHTLQSMYGC
 DLGPDGRLLR GYNQFAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 TAEQLRAYLE GTCVEWLRRY LENGKKTLQR A*

>P1;HLA:HLA01322
HLA:HLA01322 Cw*0809, 229 bases, 38C662C6 checksum.
 MRVMAPRTLT LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVQF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRNLRGYYN QSEAGSHTLQ RMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAARTAEQL RAYLEGTCVE WLRRYLENGE
 KTLQRAEHPK THVTHHPVSD HEATLRCWA*

>P1;HLA:HLA00453
HLA:HLA00453 Cw*12021, 366 bases, 2D7DBFB3 checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQADRV
 SLRNLRGYYN QSEAGSHTLQ RMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQW RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00454
HLA:HLA00454 Cw*12022, 366 bases, 9B4A8E63 checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQADRV
 SLRNLRGYYN QSEAGSHTLQ RMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQW RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA01145
HLA:HLA01145 Cw*12023, 181 bases, 210040F0 checksum.
 SHSMRYFYTA VSRPGRGEPR FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVSLRNL RGYYNQSEAG SHTLQRMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQWRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00455
HLA:HLA00455 Cw*12031, 366 bases, 9B4A8E63 checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQADRV
 SLRNLRGYYN QSEAGSHTLQ WMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQW RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA01315
HLA:HLA01315 Cw*12032, 181 bases, 85BB673C checksum.
 SHSMRYFYTA VSRPGRGEPR FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVSLRNL RGYYNQSEAG SHTLQWMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQWRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00456
HLA:HLA00456 Cw*12041, 227 bases, C1E2B6F3 checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQADRV
 NLRKLRGYYN QSEAGSHTLQ WMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQW RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRC*

>P1;HLA:HLA00457
HLA:HLA00457 Cw*12042, 366 bases, F817C34A checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQADRV
 NLRKLRGYYN QSEAGSHTLQ WMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQW RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00458
HLA:HLA00458 Cw*1205, 366 bases, 84523809 checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 NLRKLRGYYN QSEAGSHTLQ WMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQW RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00459
HLA:HLA00459 Cw*1206, 181 bases, 85BB673C checksum.
 SHSMRYFYTA VSRPGRGEPR FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVSLRNL RGYYNQSEAG SHTLQWMYGC
 DLGPDGRLLR GYDQSAYDVK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQWRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA01138
HLA:HLA01138 Cw*1207, 181 bases, 19849EDB checksum.
 SHSMRYFYTA VSRPGRGEPR FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVGLRNL RGYYNQSEAG SHTLQWMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQWRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA01413
HLA:HLA01413 Cw*1208, 366 bases, 8723D34C checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQN YKRQAQADRV
 SLRNLRGYYN QSEAGSHTLQ RMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQW RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00460
HLA:HLA00460 Cw*1301, 366 bases, FF893E1A checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQADRV
 SLRNLRGYYN QSEAGSHTLQ RMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQW RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00462
HLA:HLA00462 Cw*14021, 366 bases, F5137E10 checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRNLRGYYN QSEAGSHTLQ WMFGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQWDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00463
HLA:HLA00463 Cw*14022, 181 bases, E5B09EF2 checksum.
 SHSMRYFSTS VSRPGRGEPR FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVSLRNL RGYYNQSEAG SHTLQWMFGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQRRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00464
HLA:HLA00464 Cw*1403, 366 bases, ECF83FFA checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFSTSVSRPG RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRNLRGYYN QSEAGSHTLQ WMFGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQWDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00465
HLA:HLA00465 Cw*1404, 181 bases, 7F19D0F checksum.
 SHSMRYFSTS VSRPGRGEPR FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QADRVNLRNL RGYYNQSEAG SHTLQWMFGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQRRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA01469
HLA:HLA01469 Cw*1405, 181 bases, 5D422AF9 checksum.
 SHSMRYFSTS VSRPGRGEPR FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVSLRNL RGYYNQSEAG SHTLQWMYGC
 DLGPDGRLLR GYDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQRRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00467
HLA:HLA00467 Cw*15021, 366 bases, B192B7FB checksum.
 MRVMAPRTLL LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQN YKRQAQTDRV
 NLRKLRGYYN QSEAGSHIIQ RMYGCDLGPD GRLLRGHDQL AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA01081
HLA:HLA01081 Cw*15022, 181 bases, CFD00C69 checksum.
 SHSMRYFYTA VSRPGRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQNYKRQA QTDRVNLRKL RGYYNQSEAG SHIIQRMYGC
 DLGPDGRLLR GHDQLAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQLRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00468
HLA:HLA00468 Cw*1503, 366 bases, B192B7FB checksum.
 MRVMAPRTLL LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQN YKRQAQADRV
 NLRKLRGYYN QSEAGSHIIQ RMYGCDLGPD GRLLRGHDQL AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00469
HLA:HLA00469 Cw*1504, 366 bases, 95A07422 checksum.
 MRVMAPRTLL LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQN YKRQAQTDRV
 NLRKLRGYYN QSEAGSHIIQ RMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00470
HLA:HLA00470 Cw*15051, 366 bases, 40F54787 checksum.
 MRVMAPRTLL LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQN YKRQAQTDRV
 NLRKLRGYYN QSEAGSHIIQ RMYGCDLGPD GRLLRGHDQF AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00471
HLA:HLA00471 Cw*15052, 366 bases, FFADE527 checksum.
 MRVMAPRTLL LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQN YKRQAQTDRV
 NLRKLRGYYN QSEAGSHIIQ RMYGCDLGPD GRLLRGHDQF AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00472
HLA:HLA00472 Cw*1506, 338 bases, 3B3DB97B checksum.
 MRVMAPRTLL LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPHFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQN YKRQAQTDRV
 NLRKLRGYYN QSEAGSHIIQ RMYGCDLGPD GRLLRGHDQY AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVMAV VMCRRKSS*

>P1;HLA:HLA00473
HLA:HLA00473 Cw*1507, 181 bases, 9B919E1A checksum.
 SHSMRYFYTA VSRPGRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQNYKRQA QTDRVSLRNL RGYYNQSEAG SHIIQRMYGC
 DLGPDGRLLR GHDQLAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQLRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00474
HLA:HLA00474 Cw*1508, 181 bases, CFD00C69 checksum.
 SHSMRYFYTA VSRPGRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQNYKRQA QTDRVNLRKL RGYYNQSEAG SHIIQRMYGC
 DLGPDGRLLR GHDQLAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQRRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA01124
HLA:HLA01124 Cw*1509, 181 bases, CFD00C69 checksum.
 SHSMRYFYTA VSRPGRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQNYKRQA QTDRVNLRKL RGYYNQSEAG SHIIQRMYGC
 DLGPDGRLLR GHDQSAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQLRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA01342
HLA:HLA01342 Cw*1510, 181 bases, 15DF619D checksum.
 SHSMRYFYTA VSRPGRGEPR FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQNYKRQA QTDRVNLRKL RGYYNQSEAG SHIIQRMYGC
 DLGPDGRLLR GHDQLAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQLRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA01424
HLA:HLA01424 Cw*1511, 181 bases, CFD00C69 checksum.
 SHSMRYFYTA VSRPSRGEPH FIAVGYVDDT QFVRFDSDAA SPRGEPRAPW
 VEQEGPEYWD RETQKYKRQA QTDRVNLRKL RGYYNQSEAG SHIIQRMYGC
 DLGPDGRLLR GHDQLAYDGK DYIALNEDLR SWTAADTAAQ ITQRKWEAAR
 EAEQLRAYLE GTCVEWLRRY LENGKETLQR A*

>P1;HLA:HLA00475
HLA:HLA00475 Cw*1601, 366 bases, F6A44C9D checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRNLRGYYN QSEAGSHTLQ WMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAARAAEQQ RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHLVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00476
HLA:HLA00476 Cw*1602, 366 bases, 7495B195 checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 NLRKLRGYYN QSEAGSHTLQ WMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAARAAEQQ RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHLVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00478
HLA:HLA00478 Cw*16041, 338 bases, 3B82EB87 checksum.
 MRVMAPRTLI LLLSGALALT ETWACSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRNLRGYYN QSEAGSHTLQ WMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAARAAEQW RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHLVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSS*

>P1;HLA:HLA00481
HLA:HLA00481 Cw*1701, 372 bases, B2EDDE56 checksum.
 MRVMAPQALL LLLSGALALI ETWAGSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQADRV
 NLRKLRGYYN QSEAGSHTIQ RMYGCDLGPD GRLLRGYNQF AYDGKDYIAL
 NEDLRSWTAA DTAAQISQRK LEAAREAEQL RAYLEGECVE WLRGYLENGK
 ETLQRAERPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YTCHVQHEGL QEPCTLRWKP
 SSQPTIPNLG IVSGPAVLAV LAVLAVLAVL GAVVAAVIHR RKSSGGKGGS
 CSQAASSNSA QGSDESLIAC KA*

>P1;HLA:HLA00482
HLA:HLA00482 Cw*1702, 298 bases, 59892019 checksum.
 MRVMAPRTLI LLLSGALALI ETWAGSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQADRV
 NLRKLRGYYN QSEAGSHTIQ RMYGCDLGPD GRLLRGYNQF AYDGKDYIAL
 NEDLRSWTAA DTAAQISQRK LEAAREAEQL RAYLEGECVE WLRGYLENGK
 ETLQRAERPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YTCHVQHEGL QEPCTLRW*

>P1;HLA:HLA00993
HLA:HLA00993 Cw*1703, 338 bases, 1E87FF4B checksum.
 MRVMAPQALL LLLSGALALI ETWTGSHSMR YFYTAVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQADRV
 NLRKLRGYYN QSEAGSHTIQ RMYGCDLGPD GRLLRGYNQF AYDGKDYIAL
 NEDLRSWTAA DTAAQISQRK LEAAREAEQL RAYLEGECVE WLRGYLENGK
 ETLQRAERPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YTCHVQHEGL QEPCTLRWKP
 SSQPTIPNLG IVSGPAVLAV LAVLAVLAVL GAVVAAVI*

>P1;HLA:HLA00483
HLA:HLA00483 Cw*1801, 366 bases, 25D17FB7 checksum.
 MRVMAPRALL LLLSGGLALT ETWACSHSMR YFDTAVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQADRV
 NLRKLRGYYN QSEDGSHTLQ RMFGCDLGPD GRLLRGYNQF AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQWDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWKP
 SSQPTIPIVG IVAGLAVLVV LAVLGAVVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

>P1;HLA:HLA00484
HLA:HLA00484 Cw*1802, 366 bases, B8B14F4D checksum.
 MRVMAPRALL LLLSGGLALT ETWACSHSMR YFDTAVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQADRV
 NLRKLRGYYN QSEDGSHTLQ RMFGCDLGPD GRLLRGYNQF AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRAEHPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQWDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWKP
 SSQPTIPIVG IVAGLAVLAV LAVLGAVVAV VMCRRKSSGG KGGSCSQAAS
 SNSAQGSDES LIACKA*

