>DL;HLA:HLA00485
HLA:HLA00485 DMA*0101, 786 bases, 8F531764 checksum.
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT
 TCTGTGGCTG CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA
 TGTGGCCAGA TGACCTGCAA AACCACACAT TCCTGCACAC AGTGTACTGC
 CAGGATGGGA GTCCCAGTGT GGGACTCTCT GAGGCCTACG ACGAGGACCA
 GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT CGCCTGCCCG
 AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA
 TGGGAAAATC CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC
 TGAAGCCCCT GGAGTTTGGC AAGCCCAACA CTTTGGTCTG TTTTGTCAGT
 AATCTCTTCC CACCCATGCT GACAGTGAAC TGGCAGCATC ATTCCGTCCC
 TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT GGACTCAGCT
 TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG
 GGTACCCCGG AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG
 GCGTGGCCTT TGGCCTGGGT GTGCTGGGCA TCATCGTGGG CATTGTTCTC
 ATCATCTACT TCCGGAAGCC TTGCTCAGGT GACTGA*

>DL;HLA:HLA00486
HLA:HLA00486 DMA*0102, 564 bases, C0FF538E checksum.
 CTCCTACTCC AATGTGGCCA GATGACCTGC AAAACCACAC ATTCCTGCAC
 ACAGTGTACT GCCAGGATGG GAGTCCCAGT GTGGGACTCT CTGAGGCCTA
 CGACGAGGAC CAGCTTTTCT TCTTCGACTT TTCCCAGAAC ACTCGGGTGC
 CTCGCCTGCC CGAATTTGCT GACTGGGCTC AGGAACAGGG AGATGCTCCT
 GCCATTTTAT TTGACAAAGA GTTCTGCGAG TGGATGATCC AGCAAATAGG
 GCCAAAACTT GATGGGAAAA TCCCGGTGTC CAGAGGGTTT CCTATCGCTG
 AAGTGTTCAC GCTGAAGCCC CTGGAGTTTG GCAAGCCCAA CACTTTGGTC
 TGTTTTGTCA GTAATCTCTT CCCACCCATG CTGACAGTGA ACTGGCAGCA
 TCATTCCATC CCTGTGGAAG GATTTGGGCC TACTTTTGTC TCAGCTGTCG
 ATGGACTCAG CTTCCAGGCC TTTTCTTACT TAAACTTCAC ACCAGAACCT
 TCTGACATTT TCTCCTGCAT TGTGACTCAC GAAATTGACC GCTACACAGC
 AATTGCCTAT TGGG*

>DL;HLA:HLA00487
HLA:HLA00487 DMA*0103, 279 bases, ADE3279D checksum.
 GGGTTTCCTA TCGCTGAAGT GTTCACGCTG AAGCCCCTGG AGTTTGGCAA
 GCCCAACACT TTGGTCTGTT TTGTCAGTAA TCTCTTCCCA CCCATGCTGA
 CAGTGAACTG GCAGCATCAT TCCGTCCCTG TGGAAGGATT TGGGCCTACT
 TTTGTCTCAG CTGTCGATGC ACTCAGCTTC CAGGCCTTTT CTTACTTAAA
 CTTCACACCA GAACCTTCTG ACATTTTCTC CTGCATTGTG ACTCACGAAA
 TTGACCACTA CACAGCAATT GCCTATTGG*

>DL;HLA:HLA00488
HLA:HLA00488 DMA*0104, 279 bases, 70E05A15 checksum.
 GGGTTTCCTA TCGCTGAAGT GTTCACGCTG AAGCCCCTGG AGTTTGGCAA
 GCCCAACACT TTGGTCTGTT TTGTCAGTAA TCTCTTCCCA CCCATGCTGA
 CAGTGAACTG GCAGCATCAT TCCATCCCTG TGGAAGGATT TGGGCCTACT
 TTTGTCTCAG CTGTCGATGG ACTCAGCTTC CAGGCCTTTT CTTACTTAAA
 CTTCACACCA GAACCTTCTG ACATTTTCTC CTGCATTGTG ACTCACGAAA
 TTGACTGCTA CACAGCAATT GCCTATTGG*

