>P1;HLA:HLA00489
HLA:HLA00489 DMB*0101, 263 bases, 7419983E checksum.
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL
 LTCWDPEENK MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH
 TQPFWGSLTN RTRPPSVQVA KTTPFNTREP VMLACYVWGF YPAEVTITWR
 KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL ALTPSYGDTY TCVVEHIGAP
 EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW RRAGHSSYTP
 LPGSNYSEGW HIS*

>P1;HLA:HLA00490
HLA:HLA00490 DMB*0102, 94 bases, 73D5CC44 checksum.
 PPSVQVAKTT PFNTREPVML ACYVWGFYPA EVTITWRKNG KLVMPHSSEH
 KTAQPNGDWT YQTLSHLALT PSYGDTYTCV VEHIGAPEPI LRDW*

>P1;HLA:HLA00491
HLA:HLA00491 DMB*0103, 94 bases, ED7628DE checksum.
 PPSVQVAKTT PFNTREPVML ACYVWGFYPA EVTITWRKNG KLVMPHSSAH
 KTAQPNGDWT YQTLSHLALT PSYGDTYTCV VEHTGAPEPI LRDW*

>P1;HLA:HLA00492
HLA:HLA00492 DMB*0104, 80 bases, 453718BE checksum.
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SVHKTAQPNG
 DWTYQTLSHL ALTPSYGDTY TCVVEHTGAP*

>P1;HLA:HLA00493
HLA:HLA00493 DMB*0105, 175 bases, A326EF74 checksum.
 ESTCLLDDAG TPKDFTYCIS FNKDLLTCWD PEENKMAPCE FGVLNSLANV
 LSQHLNQKDT LMQRLRNGLQ NCATHTQPFW GSLTNRTRPP SVQVAKTTPF
 NTREPVMLAC YVWGFYPAEV TITWRKNGKL VMPHSSVHKT AQPNGDWTYQ
 TLSHLALTPS YGDTYTCVVE HIGAP*

>P1;HLA:HLA01083
HLA:HLA01083 DMB*0106, 188 bases, FC7C407C checksum.
 GFVAHVESTC LLDDAGTPKD FTYCIFFNKD LLTCWDPEEN KMAPCEFGVL
 NSLANVLSQH LNQKDTLMQR LRNGLQNCAT HTQPFWGSLT NRTRPPSVQV
 AKTTPFNTRE PVMLACYVWG FYPAEVTITW RKNGKLVMPH SSEHKTAQPN
 GDWTYQTLSH LALTPSYGDT YTCVVEHTGA PEPILRDW*

