# Style Checking Action
# Runs only on one OS/Python version.

name: Style Checking (Flake8 & Black)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Installing dependencies via pre-commit
      run: |
        python -m pip install pre-commit
        pre-commit install --install-hooks

    - name: Run pre-commit
      run: |
        pre-commit run -a